name: flutter_architecture_sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  clock: ^1.1.2
  cloud_firestore: ^5.6.9
  collection: ^1.19.1
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.6.0
  meta: ^1.16.0
  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  url_strategy: ^0.3.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.6.7
  flutter_gen_runner: ^5.10.0
  flutter_svg: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  # mockito: ^5.4.6
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter_gen:
  output: lib/ui/style/gen/
  integrations:
    flutter_svg: true
  assets:
    outputs:
      class_name: Assets

flutter:
  uses-material-design: true
  assets:
    # - assets/svg/
    - assets/fonts/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSansJP-SemiBold.ttf
          weight: 600
